### ISSUE TITLE
Full: Infra - Serve the game as a Docker image

### ISSUE THREAD

**Issue by ThomasFerro** [ThomasFerro/armadora#10]
- [ ] Dockerfile: Write multi-stage file with the front (test + build) and the back (test + build), then serve the artifacts in an image from scratch;
- [ ] CI: Remove the Go Github Action and use a Docker Action instead.

**Comment by ThomasFerro** [comment]
Expose K8S services => Use external IP, example:
```
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 1.2.4.120
```
